### ISSUE TITLE
There's horizontal scroll 

### ISSUE THREAD

**Issue by webgtx** [qtile/qtile.org#55] opened 2023-10-05 21:44 UTC
![image](https://github.com/qtile/qtile.org/assets/62614322/c1b8fab8-6ba0-4e03-b4a3-dacd2d393341)

**Chromium Version 114.0.5735.110 (Official Build) (64-bit)**

**Comment by tych0** [comment] 2023-10-05 22:42
Yeah, I've noticed a few of these weirdnesses too. Oddly, I can't reproduce your report with current chrome, but there is scrolling oddities if e.g. the viewport is too small for the width of the page. It would be great if someone could send a patch to fix the CSS.

**Comment by tych0** [comment] 2024-02-21 21:46
Fix was merted, I forgot to close this.

**Closed by tych0** 2024-02-21 21:46 UTC
